# special forms pokemon
SPECIAL_FORMS = {"Vivillon": ["Vivillon-Archipelago","Vivillon-Continental","Vivillon-Elegant","Vivillon-Garden","Vivillon-High Plains","Vivillon-Icy Snow","Vivillon-Jungle","Vivillon-Marine","Vivillon-Modern","Vivillon-Monsoon","Vivillon-Ocean","Vivillon-Polar","Vivillon-River","Vivillon-Sandstorm","Vivillon-Savanna","Vivillon-Sun","Vivillon-Tundra"],
'Flabebe': ["Flabebe-Blue","Flabebe-Orange","Flabebe-White","Flabebe-Yellow"],
'Floette': ["Floette-Blue","Floette-Orange","Floette-White","Floette-Yellow"],
'Florges': ["Florges-Blue","Florges-Orange","Florges-White","Florges-Yellow"],
'Furfrou': ["Furfrou-Dandy","Furfrou-Debutante","Furfrou-Diamond","Furfrou-Heart","Furfrou-Kabuki","Furfrou-LaReine","Furfrou-Matron","Furfrou-Pharaoh","Furfrou-Star"],
'Minior': ["Minior-Orange","Minior-Yellow","Minior-Green","Minior-Blue","Minior-Indigo","Minior-Violet","Minior-Meteor"],
'Alcremie': ["Alcremie-Ruby-Cream","Alcremie-Matcha-Cream","Alcremie-Mint-Cream","Alcremie-Lemon-Cream","Alcremie-Salted-Cream","Alcremie-Ruby-Swirl","Alcremie-Caramel-Swirl","Alcremie-Rainbow-Swirl"],
'Tatsugiri': ["Tatsugiri-Droopy","Tatsugiri-Stretchy"],
'Unown': ["Unown-A","Unown-B","Unown-C","Unown-D","Unown-E","Unown-F","Unown-G","Unown-H","Unown-I","Unown-J","Unown-K","Unown-L","Unown-M","Unown-N","Unown-O","Unown-P","Unown-Q","Unown-R","Unown-S","Unown-T","Unown-U","Unown-V","Unown-W","Unown-X","Unown-Y","Unown-Z","Unown-Exclamation","Unown-Question"],
'Burmy': ["Burmy-Sandy","Burmy-Trash"],
'Shellos': ["Shellos-East","Shellos-West"],
'Gastrodon': ["Gastrodon-East","Gastrodon-West"],
'Deerling': ["Deerling-Spring","Deerling-Summer","Deerling-Autumn","Deerling-Winter"],
'Sawsbuck': ["Sawsbuck-Spring","Sawsbuck-Summer","Sawsbuck-Autumn","Sawsbuck-Winter"],
'Dudunsparce-*': ["Dudunsparce-Three-Segment"]}